import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import MySessionProvider from "@/MySessionProvider/MySessionProvider";
import NavbarWrapper from "./_components/NavbarWrapper/NavbarWrapper";
import Footer from "./_components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <MySessionProvider>
          <NavbarWrapper />
          <main className="mt-22">
            <ToastContainer />
            {children}
          </main>
          <Footer/>
        </MySessionProvider>

      </body>
    </html>
  );
}
